[package]
name = "rprobe"
version = "0.1.0"
edition = "2021"
authors = ["Volker Schwaberow <volker@schwaberow.de>"]
homepage = "https://github.com/vschwaberow/rprobe.git"
repository = "https://github.com/vschwaberow/rprobe.git"
description = "A simple tool to probe a remote host http or https connection"
keywords = ["rust", "network", "security", "probe", "http", "https"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
threadpool = "1.8.1"
tokio = { version = "1.21.0", features = ["full"] }
